name: Check nix formatting
on:
  push:
    paths:
      - "**/*.nix"
jobs:
  nixfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - name: Run nixfmt check
        run: |
          nix run nixpkgs#nixfmt -- --check **/*.nix
